services:
  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    ports:
      - "8989:8989"
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g
      - ACTION=server
      - CONFIG=/config/config.yml
    volumes:
      - ./tools/graphhopper/volumes/graphhopper_data:/data
      - ./tools/graphhopper/config:/config
    entrypoint:  ["./graphhopper.sh", "-c", "/config/config.yaml"]

  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm
    ports:
      - "5000:5000"
    volumes:
      - ./tools/osrm/volumes/osrm_data:/data
    command: ["osrm-routed","--algorithm=mld", "/data/newson_krumm_reconstructed.osrm"]
  
  osrm_frontend:
    image: osrm/osrm-frontend
    container_name: osrm_frontend
    ports:
      - "9966:9966"
    environment:
      - OSRM_BACKEND_URL=http://osrm:5000
    depends_on:
      - osrm