services:
  import-map:
    image: israelhikingmap/graphhopper:latest
    container_name: import_osm
    environment:
      - JAVA_OPTS=-Xmx8g -Xms8g
      - FILE=/osm/newson_krumm_reconstructed.osm.pbf
      - ACTION=import
    volumes:
      - ./graphhopper_data:/data
      - ./osm/pbf:/osm
    
  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    ports:
      - "8989:8989"
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g
      - ACTION=server
    volumes:
      - ./graphhopper_data:/data
        
