import os
import gzip
import subprocess
import shutil
from pathlib import Path
import tempfile


def resolve_absolute_path(relative_path: str) -> Path:
    return Path(relative_path).resolve().absolute()


# config
N_SIMULATIONS = 500
SIMULATION_TIME = 3600  # in seconds
SIMULATION_STEP = 0.5  # in seconds

# Paths
SUMO_HOME = os.environ.get("SUMO_HOME", "/usr/share/sumo")
NETWORK_FILE = resolve_absolute_path(
    "./sumo/simulations/ohare-chicago/ohare-filtered.net.xml"
)
TAZ_FILE = resolve_absolute_path(
    "./sumo/simulations/ohare-chicago/ohare-filtered.taz.add.xml"
)
TRIPS_FILE = resolve_absolute_path(
    "./sumo/simulations/ohare-chicago/ohare-filtered.trips.xml"
)
OUTPUT_PATH = resolve_absolute_path("./sumo/simulations/ohare-chicago")

BASENAME = Path(NETWORK_FILE).name.strip(".net.xml")
OUTPUT_FILE_ROUTES = Path(OUTPUT_PATH) / f"{BASENAME}.rou.xml"
OUTPUT_PATH.mkdir(parents=True, exist_ok=True)


def try_parse_int(value: str, default: int | None = None) -> int | None:
    try:
        return int(value)
    except ValueError:
        return default


def main():
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        print(f"Using temporary directory: {temp_path}")

        # fmt: off
        cmd = [
            "python3",
            f"{SUMO_HOME}/tools/assign/duaIterate.py",
            "-n", NETWORK_FILE,
            "-t", TRIPS_FILE,
            "-D", TAZ_FILE,
            "-R", str(SIMULATION_TIME),
            "--gzip",
            "--clean-alt",
            "--output-last",
            "-l", str(N_SIMULATIONS),
            "sumo--step-length", str(SIMULATION_STEP),
        ]
        # fmt: on

        subprocess.run(cmd, check=True, cwd=temp_path)
        print("SUMO simulation completed.")

        # Find the last generated .rou.xml.gz file
        out_files = os.listdir(temp_path)
        simulation_files = [
            parsed for f in out_files if (parsed := try_parse_int(f, None)) is not None
        ]
        if not simulation_files:
            raise FileNotFoundError("No file .rou.xml was generated by SUMO.")

        last_simulation = f"{max(simulation_files):03d}"

        final_rou = temp_path / last_simulation / f"{BASENAME}_{last_simulation}.rou.gz"
        if not final_rou.exists():
            raise FileNotFoundError(f"The expected file {final_rou} was not found.")

        with gzip.open(final_rou, "rb") as f_in:
            with open(OUTPUT_FILE_ROUTES, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)

    print(f"Final routes saved in: {OUTPUT_FILE_ROUTES}")


if __name__ == "__main__":
    main()
