import os
import gzip
import subprocess
import shutil
from pathlib import Path
import tempfile


def resolve_absolute_path(relative_path: str) -> Path:
    return Path(relative_path).resolve().absolute()


# config
N_SIMULATIONS = 500
SIMULATION_TIME = 3600  # in seconds
SIMULATION_STEP = 0.5  # in seconds

# Paths
SUMO_HOME = os.environ.get("SUMO_HOME", "/usr/share/sumo")
BASE_PATH = resolve_absolute_path("./sumo/simulations/ohare-chicago-junctionless")

NETWORK_FILE = BASE_PATH / "network.net.xml"

TAZ_FILE = BASE_PATH / "grid_taz.add.xml"
TRIPS_FILE = BASE_PATH / "random_trips.trips.xml"
OUTPUT_PATH = BASE_PATH
OUTPUT_FILE_ROUTES = OUTPUT_PATH / "optimized_routes.rou.xml"
OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

def try_parse_int(value: str, default: int | None = None) -> int | None:
    try:
        return int(value)
    except ValueError:
        return default

def main():
    with tempfile.TemporaryDirectory(delete=False) as temp_dir:
        temp_path = Path(temp_dir)
        print(f"Using temporary directory: {temp_path}")

        # fmt: off
        cmd = [
            "python3",
            f"{SUMO_HOME}/tools/assign/duaIterate.py",
            "-n", NETWORK_FILE,
            "-t", TRIPS_FILE,
            "-D", TAZ_FILE,
            "-R", str(SIMULATION_TIME),
            "--gzip",
            "--clean-alt",
            "--output-last",
            "-l", str(N_SIMULATIONS),
            "sumo--step-length", str(SIMULATION_STEP),
        ]
        # fmt: on

        exit_early = False
        try:
            subprocess.run(cmd, check=True, cwd=temp_path)
            print("SUMO simulation completed.")
        except KeyboardInterrupt:
            print("Simulation interrupted by user.")
            exit_early = True
        except subprocess.CalledProcessError as e:
            print(f"An error occurred during the SUMO simulation: {e}")
            return
            
        

        # Find the last generated .rou.xml.gz file
        out_files = os.listdir(temp_path)
        simulation_files = [
            parsed for f in out_files if (parsed := try_parse_int(f, None)) is not None
        ]
        if not simulation_files:
            raise FileNotFoundError("No file was generated by SUMO.")

        last_simulation = max(simulation_files)
        if exit_early:
            print(f"Using the last successfully generated simulation: {last_simulation-1:03d}")
            if last_simulation == 0:
                raise ValueError("No valid simulation was completed.")
            last_simulation -= 1
        
        last_simulation = f"{last_simulation:03d}"

        filename = TRIPS_FILE.name.replace(".trips.xml", "")
        print(filename)
        final_rou_path = temp_path / last_simulation / f"{filename}_{last_simulation}.rou.gz"
        if not final_rou_path.exists():
            raise FileNotFoundError(f"The expected file {final_rou_path} was not found.")

        with gzip.open(final_rou_path, "rb") as f_in:
            with open(OUTPUT_FILE_ROUTES, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)

    print(f"Final routes saved in: {OUTPUT_FILE_ROUTES}")


if __name__ == "__main__":
    main()
